[package]
name = "snoozy-macros"
version = "0.1.0"
authors = ["Tomasz Stachowiak <h3@h3.gd>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.26", features = ["full", "extra-traits", "parsing", "printing"] }
quote = "*"
proc-macro2 = "*"
twox-hash = "1.1.2"